[package]
name = "ltbridge"
version = "0.1.0"
edition = "2021"
rust-version = "1.79.0"
authors = ["caibirdme <492877816@qq.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    ".",
    "logql",
    "traceql"
]

[dependencies]
anyhow = "1.0.86"
async-trait = "0.1.81"
axum = { version = "0.7.5", features = ["default"] }
axum-extra = { version = "0.9.3", features = ["protobuf"] }
axum-valid = "0.19.0"
chrono = { version = "0.4.38", features = ["serde"] }
clickhouse = "0.11.6"
config = { version = "0.14.0" }
databend-driver = { version = "0.19.2" }
dyn-clone = "1.0.17"
hex = { version = "0.4.3" }
http = "1.1.0"
humantime-serde = { version = "1.1.1" }
itertools = { version = "0.13.0" }
lazy_static = "1.5.0"
logql = { path = "logql" }
moka = { version = "0.12.8", features = ["default", "sync"] }
opentelemetry = { version = "0.23.0", features = ["metrics"] }
opentelemetry-prometheus = "0.16.0"
opentelemetry-proto = { version = "0.6.0", features = ["full"] }
opentelemetry-semantic-conventions = { version = "0.16.0" }
opentelemetry_sdk = { version = "0.23.0", features = ["metrics"] }
ordered-float = { version = "4.2.1" }
prometheus = "0.13.4"
prost = { version = "0.12.6" }
reqwest = { version = "0.12.5", features = ["json", "native-tls-vendored"], default-features = false }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = { version = "1.0.120" }
serde_with = { version = "3.8.3", features = ["json"] }
thiserror = { version = "1.0.62" }
tokio = { version = "1.38.1", features = ["full"] }
tokio-stream = { version = "0.1.15" }
tower = { version = "0.4.13" }
tower-http = { version = "0.5.2", features = [
    "trace",
    "timeout",
    "compression-gzip",
    "decompression-gzip",
] }
traceql = { path = "traceql" }
tracing = { version = "0.1.40" }
tracing-subscriber = { version = "0.3.18", features = [
    "default",
    "env-filter",
    "json",
] }
url = "2.5.2"
validator = { version = "0.18.1", features = ["derive"] }

[dev-dependencies]
pretty_assertions = "1.4.0"
serde_urlencoded = "0.7.1"
serde_yaml = "0.9.34"
sqlparser = "0.48.0"

[build-dependencies]
anyhow = "1.0.82"
prost-build = { version = "0.13.1", features = ["default", "cleanup-markdown"] }
