version: 0.8

default_index_root_uri: s3://quickwit/indexes
metastore_uri: postgres://quickwit:quickwit123@postgres:5432/quickwit

storage:
  s3:
    flavor: minio
    endpoint: http://qwminio:9000
    access_key_id: "minio"
    secret_access_key: "minio123"
    force_path_style_access: true
    region: us-east-1
