[package]
name = "common"
version = "0.1.0"
edition = "2021"
rust-version = "1.76.0"
authors = ["caibirdme <492877816@qq.com>"]

[dependencies]
anyhow = { version = "1.0.93" }
chrono = { workspace = true }
