apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki_uid_1
    isDefault: true
    access: proxy
    url: http://host.docker.internal:6778
    jsonData:
      maxLines: 1000
      derivedFields:
        # Field with internal link pointing to data source in Grafana.
        # datasourceUid value can be anything, but it should be unique across all defined data source uids.
        - datasourceUid: tempo_uid_1
          matcherRegex: trace_id
          matcherType: label
          name: trace_id
          url: "$${__value.raw}"
          urlDisplayLabel: JumpToTrace
  - name: Tempo
    type: tempo
    uid: tempo_uid_1
    access: proxy
    url: http://host.docker.internal:6778
    jsonData:
      tracesToLogsV2:
        customQuery: true
        datasourceUid: loki_uid_1
        query: '{trace_id="$${__span.traceId}", span_id="$${__span.spanId}"}'
        spanEndTimeShift: 5m
        spanStartTimeShift: -5m
