name: PR Check

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.80.0
        profile: minimal
        override: true
    - name: Install binstall
      run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
    - name: Install checkers
      uses: actions-rs/cargo@v1
      with:
        command: binstall
        args: -y cargo-sort
    - name: cargo sort check
      uses: actions-rs/cargo@v1
      with:
        command: sort
        args: -c
    - name: Fmt check
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
    - name: Clippy check
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings
    - name: Unit Test
      uses: actions-rs/cargo@v1
      with:
        command: test
