name: PR Check

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.78.0
        profile: minimal
        override: true
    - name: Fmt check
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
    - name: Clippy check
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --target x86_64-unknown-linux-musl -- -D warnings
        use-cross: true
    - name: Unit Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        use-cross: true
        args: --target x86_64-unknown-linux-musl
