name: PR Check

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install protoc
      uses: arduino/setup-protoc@v2
      with:
        version: '25.1'
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@1.84.0
      with:
        components: rustfmt, clippy

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    
    - name: Install cargo-sort
      uses: taiki-e/install-action@cargo-sort
    
    - name: Check format
      run: cargo fmt -- --check
    
    - name: Check cargo.toml sorting
      run: cargo sort -c -w
    
    - name: Clippy
      run: cargo clippy --all-features
    
    - name: Run tests
      run: cargo test --all-features
